spring:
    jpa:
        hibernate:
            ddl-auto: create
    datasource:
        url: jdbc:sqlite:orders.db
        driver-class-name: org.sqlite.JDBC
server:
    error:
        include-message: always